sudo: required

language: ruby

services:
  - docker
  
#cache:
#  directories:
#    - /home/travis/docker/  
  
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
#  - if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi
  - git submodule update --init --recursive || true
  - git submodule foreach git stash
  - git submodule foreach git rebase
  - du -a src/open_nsfw
  
env:
  global:
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz

install:
  - cd scripts
  - travis_wait 45 docker build -q -t caffe:cpu https://raw.githubusercontent.com/BVLC/caffe/master/docker/standalone/cpu/Dockerfile
  - ./flask_nsfw build
#  - if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then mkdir -p $(dirname ${DOCKER_CACHE_FILE}) ; docker save $(docker history -q ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE}; fi

script:
  - ./flask_nsfw test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.example.com
    docker push USER/REPO;
    fi
