#!/usr/bin/env bash

# name of the Docker image to build
NAME=flask_nsfw

# host port that will be connected to container's port 5000
PORT=5000

# ensure a consistent working directory
SOURCE="${BASH_SOURCE[0]}"
# resolve $SOURCE until the file is no longer a symlink
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
cd $DIR

main () {
  if [ "$1" = "dev" ]; then
    VOLUMES="-v $DIR/../src:/opt/flask_nsfw"
    dispatch $2
  else
    dispatch $1
  fi
}

dispatch () {
  case "$1" in
    build)
      docker build -t $NAME -f Dockerfile ..
      ;;
    test)
      docker run -t -i $VOLUMES flask_nsfw \
        sh -c "cd /opt/flask_nsfw && python -m flask_nsfw.test"
      ;;
    run)
      docker run -t -i $VOLUMES -p $PORT:5000 flask_nsfw
      ;;
    shell)
      docker run -t -i $VOLUMES flask_nsfw \
        bash
      ;;
    *)
      echo $"Usage: $0 [dev] {build|run|shell|test}"
      exit 1
      ;;
  esac
}

main "$@"
